services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
    depends_on:
      - mongo

  backend:
    build:
      args:
        MONGO_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    
  frontend:
    build:
      args:
        VITE_API_URL: http://localhost:5000
        VITE_WEATHER_URL: https://api.weather.gov
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend